### ISSUE TITLE
@href on folder  : bad uri construction 

### ISSUE THREAD

**Issue by karrayhamdi** [cmarchand/gaulois-pipe#16]
hi,

when i pass a parameter (as uri) to the config file, for treatement file source, i catch an exception on the folder uri. I pass a parameter like : "file:/toto" and the exception message said uri = 'c:\titi\project\file\toto : invalid uri. 
[gp.zip](https://github.com/cmarchand/gaulois-pipe/files/806004/gp.zip)

**Comment by cmarchand** [comment]
sources/folder/@href was always constructed as a relative path to current directory.
Now constructs it as a absolute URI, and fallback to File relative to current dir.
Added a UT in ConfigUtilTest
