### ISSUE TITLE
Passing a ThreadFactory to Gaulois-pipe

### ISSUE THREAD

**Issue by Betta78** [cmarchand/gaulois-pipe#19]
Hello christophe,
  Would you mind to add the possiblity to pass a ThreadFactory to gaulois-pipe rather than using it's own ThreadFactory for threads instantiation?
  Use case :  Customer is using its own specific ThreadFactory compatible with a specific protocol
   
Thank you

**Comment by cmarchand** [comment]
Sure, it shouldn't be too difficult.

**Comment by cmarchand** [comment]
Solved by commit #eae438f
I'm gonna publish a 1.01.10 ASAP, probably today.
