### ISSUE TITLE
output attributes (@indent, @cdata-section-elements)

### ISSUE THREAD

**Issue by ahu-els** [cmarchand/gaulois-pipe#2]
I'm trying to get an indented output including CDATA elements.
My pipeline looks like this:
    <pipe mutiThreadMaxSourceSize="24349456" nbThreads="4">
…
        <output id="main" 
            method="xml" encoding="UTF-8" **indent="yes" cdata-section-elements="elem1 elem2**">
</pipe>
I also tried to put these attributes in my last stylesheet.
But neither in the configuration file, neither in the last stylesheet seem to work, the output is not indented and do not contain the CDATA elements.

**Comment by cmarchand** [comment]
Fixed by 5b6fbea
1.00.01-SNAPSHOT
