### ISSUE TITLE
<choose> as first element of pipe

### ISSUE THREAD

**Issue by Marc95** [cmarchand/gaulois-pipe#23]
When a "choose" is the first element of a pipe it is not executed.
I have to put an "xslt" with an identity xsl before it.
When a choose is the last element of a pipe, there is an error.
release 1.01.11

**Comment by cmarchand** [comment]
All pipe(s) must start with a xslt. This limitation comes from Saxon API, where XSLTTransformer must be the root of a pipeline.
It try to remove it from pipe embedded in tee's, but it is not simple.

Could you give a sample of a pipe that ends with a choose ?
Christophe

**Comment by cmarchand** [comment]
A `choose` must not contains an `output`.
A `pipe` must be terminated.
So a `pipe` must not be ended by a `choose`. You mut put a `output` to terminate a `pipe`.
