### ISSUE TITLE
New feature : OutputStream output in listener mode

### ISSUE THREAD

**Issue by arkamy** [cmarchand/gaulois-pipe#24]
Possibility to get OutputStream instead of files as gaulois-pipe output in listener mode
Thanks

**Comment by cmarchand** [comment]
Probably a new public method that let you give the OutputStream you want to connect to gaulois-pipe output.
There will probably have few limitations : 
- each output you want to map to an OutputStream MUST have an @id
- output-base-uri will be set to the one that would be used if a normal file were used

Is it correct for you ?

**Comment by arkamy** [comment]
It will be perfect. Thanks

**Comment by cmarchand** [comment]
Please give a try to 1.02.00-RC2, just published, and have a look to 

`public void execute(Pipe pipe, ParametrableFile input, MessageListener listener, Map<String,OutputStream> ... outputs)`

Christophe

**Comment by cmarchand** [comment]
Release 1.03.00 is the final delivrey for this issue.
Best regards
