### ISSUE TITLE
Accent in the name of souce file

### ISSUE THREAD

**Issue by wondergarance** [cmarchand/gaulois-pipe#25]
Hello,

I found that the gaulois-pipe doesn't accept the accent characters in the name of a source file.
For example: ED Proc**é**dures collectives.xml
I should rename it as ED Proc**e**dures collectives.xml

Qian

**Comment by cmarchand** [comment]
I've added a test case for this, `GauloisPipeTest.testIssue25(), and I can not reproduce the problem.
Could you please provide a test case so I could reproduce the problem.

Thanks in advance,
Christophe

**Comment by cmarchand** [comment]
This is not a bug. In the sample you provided, you load sources with :
```xml
<folder href="." pattern="p{ASCII}+\.[xml|XML]$"/>
```
"é" does not match `p{ASCII}`

**Comment by wondergarance** [comment]
Thank you. 
I found the problem, it was in my config file of Gaulois-pipe. The regular expression for sources/folder/@pattern was \p{ASCII}+\.(xml|XML)$, it doesn't accept accent in the name of the file.
I corrected it to .+\.(xml|XML)$
