### ISSUE TITLE
Make public Pipe.setMultithreadedMaxSourceSize(int) et Pipe.setNbThread(int)

### ISSUE THREAD

**Issue by fadjer** [cmarchand/gaulois-pipe#26]
Hi Christophe,

I need to set Pipe.setMultithreadedMaxSourceSize(int) and Pipe.setNbThread(int) at runtime. Currently those methods are not public.

Many Thanks.

**Comment by cmarchand** [comment]
Have a look at 1.03.01. It is available on Maven central.
http://repo1.maven.org/maven2/top/marchand/xml/gaulois-pipe/1.03.00/
