### ISSUE TITLE
open a jar:file:

### ISSUE THREAD

**Issue by Marc95** [cmarchand/gaulois-pipe#3]
I have a problem to open an xslt file in a jar file.
I use the jar;file: URI syntax.
Perhaps is it becvause my xslt file opens other xslt files as import?

Marc

**Comment by cmarchand** [comment]
Have you checked the https://github.com/cmarchand/gaulois-pipe/blob/master/src/test/java/fr/efl/chaine/xslt/GauloisPipeTest.java / testXslInJar() UT ?
Then, if you import / include another XSL, with a relative path, it should work.

Please provides a test-case otherwise.

Thanks,
Christophe

**Comment by cmarchand** [comment]
Hi Marc,
Is this problem solved ?

Regards,
Christophe

**Comment by Marc95** [comment]
Yes and now with the cp: it's easier to do!
Marc

**Comment by cmarchand** [comment]
Glad this new feature helps !
Best,
Christophe
