### ISSUE TITLE
Multiple <xslt> in <when>

### ISSUE THREAD

**Issue by ahu-els** [cmarchand/gaulois-pipe#31]
Hello,

I tried to run 2 xsl inside <when> :

  <pipe mutiThreadMaxSourceSize="24349456" nbThreads="4" traceOutput="#logger">
    <xslt href="cp:/common/xsl/identity.xsl"/>
    <choose>
      <when test="/toto'">
        <xslt href="cp:/titi.xsl"/>
        <xslt href="cp:/tata.xsl"/>
      </when>
      <otherwise>
        <xslt href="cp:/common/xsl/identity.xsl"/>
      </otherwise>
    </choose>
    <xslt href="cp:/common/xsl/identity.xsl"/>
    <output id="main" method="xml" encoding="UTF-8" indent="no">
      <folder absolute="$[CONTEXT.URI]/$[resStep]"/>
      <fileName name="$[input-basename].xml"/>
    </output>
  </pipe>

But it seems that only the first one is executed.

I made my pipe worked, by using 2 <choose> with only 1 <xslt> inside <when>

Can you check this point, to see you're having the same issue ? 
I'm using version 1.01.11.

Thanks

**Comment by cmarchand** [comment]
Reproduced. Test case updated. I'm now searching why !

**Comment by cmarchand** [comment]
This one a little bit tricky. But solved.
Should be available in a (near) future 1.03.03
