### ISSUE TITLE
The convert() method for an atomic Datatype should not (always) split the input value

### ISSUE THREAD

**Issue by AxelCourt** [cmarchand/gaulois-pipe#35]
Hi,

The `convert()` method for an atomic Datatype (see `DatatypeFactory.java` line 124) "conveniently" splits the input value as if it were always supposed to be a XPath sequence. That is: beginning / ending parenthesis "(" ")" are removed and commas "," are used as a sequence value delimiter.

But there are cases where this behaviour is wrong: for instance, if a parameter is defined as "xs:string" in a gaulois-pipe configuration file, it should mean that the input value must be taken "as is", and commas or parenthesis should not be treated as special characters.
I actually have several string parameters where I use commas, and I know I do not want them to be splitted!

If there a way to deactivate this functionality when it is not wanted?
Maybe if the parameter type is not a multiple one?

Thanks!

**Comment by cmarchand** [comment]
Could you give a precise example ?

**Comment by AxelCourt** [comment]
Some examples:
```
<param name="formatJson" value="{ 'SVG':['PNG'], 'GIF':['PNG'] }" as="xs:string"/>
<param name="overrideTitle" value="Un titre, avec une virgule" as="xs:string"/>
<param name="pattern" value="$1, $2 - $3" as="xs:string"/>
```

**Comment by cmarchand** [comment]
1.03.04-RC3

**Comment by AxelCourt** [comment]
Thanks, it seems to work fine now!
