### ISSUE TITLE
Error when calling external xslt file

### ISSUE THREAD

**Issue by karrayhamdi** [cmarchand/gaulois-pipe#38]
Hi,

i get an error whe i call an external xslt, with absolute path or uri. 
href is considered as path here

    private File getFile() throws URISyntaxException {
     if(file==null) {
       if(href.startsWith("jar:")) {
         file = new File(new URI(href));
       } else if(href.startsWith("cp:")) {
         // nope
       } else {
         file = new File(href);
       }
     }
     return file;
    }
and as uri here 

    private XsltTransformer getXsltTransformer(String href, HashMap<QName,ParameterValue> parameters)
        throws MalformedURLException, SaxonApiException, URISyntaxException, FileNotFoundException, IOException {
      String __href = (String)ParametersMerger.processParametersReplacement(href, parameters);
      LOGGER.debug("loading "+__href);
      XsltExecutable xsl = xslCache.get(__href);
      if(xsl==null) {
        LOGGER.trace(__href+" not in cache");
        try {
          Source xslSource = getUriResolver().resolve(href, getCurrentDirUri());
          if(xslSource==null) {
            throw new FileNotFoundException("Unable to resolve "+href);
          }

The best way, il think, is to consider href as an uri everywhere.

thanks :)

**Comment by cmarchand** [comment]
Could you provide your config file and the release of gaulois-pipe you use, to be able to create a test case ?

**Comment by karrayhamdi** [comment]
here is it :)

**Comment by cmarchand** [comment]
And the value of `xslt-file-uri` your provide ?

**Comment by karrayhamdi** [comment]
i tried both "file:/d:/..../toto.xsl" and "d:/.../toto.xsl".

**Comment by cmarchand** [comment]
Here is a piece of code, to disply files as URI.
![dir_output log](https://user-images.githubusercontent.com/659571/37839316-68d87b52-2eba-11e8-9d09-3b24da1508de.png)
This image shows the File I want to log as URI

The code is :

    public static void main(String[] args) {
        File local = new File(".");
        FileSystem fs = FileSystems.getDefault();
        Path d = null;
        for(Path path: fs.getRootDirectories()) {
            if(path.toString().toLowerCase().startsWith("d")) {
                d = path;
                break;
            }
        }
        if(d==null) {
            System.err.println("d: not found");
            return;
        }
        File fD = d.toFile();
        File devel = new File(fD, "devel");
        File output = new File(devel, "output.log");
        System.out.println("output.toString(): "+output.toString());
        System.out.println("output.getAbsolutePath: "+output.getAbsolutePath());
        System.out.println("output.toURI().toString(): "+output.toURI().toString());
    }

Output of this code is :

    output.toString(): D:\devel\output.log
    output.getAbsolutePath: D:\devel\output.log
    output.toURI().toString(): file:/D:/devel/output.log

I think, if you try `file:/D:/.../toto.xsl`, it should work correctly.

**BUT** : this is not a good practise. As properties may change from input file to input file, XSL won't be compiled when gaulois-pipe starts, but when required, and won't be cached, so will be compiled each time is need. You'd better use constant XSLT URIs.

Tell me if this solve your problem.

**Comment by karrayhamdi** [comment]
I already tried that but still not working for me.
This is my [project](https://bitbucket.org/HamdiKarray/html-tnr/commits/b1def7953923602cf9611ab0a8b7f8951894db72).
This project allow you performing tnr on html. It need some xml files, 2 xslt and a working directory.
To run it : 
main class : 
`eu.els.sie.efl.html.tnr.Run`

params :
`-xmlDirPath D:\08-ELS\15-CONVBIL\00-DATA\xml -workDirPath D:\08-ELS\15-CONVBIL\00-DATA\work -originalXsltFilePath D:\08-ELS\11-BOFIP\sie-efl-sgml2html\src\main\xslt\codescV2.xslt  -revisedXsltFilePath D:\08-ELS\15-CONVBIL\01-DEV\sie-efl-sgml2html\src\main\xslt\codescV2.xslt`

I get this exception (note that file:/ is in the middle of the path) : 

```
Caused by: fr.efl.chaine.xslt.InvalidSyntaxException: D:\08-ELS\15-CONVBIL\01-DEV\html-tnr\file:\D:\08-ELS\11-BOFIP\sie-efl-sgml2html\src\main\xslt\codescV2.xslt does not exists or is not a regular file
	at fr.efl.chaine.xslt.config.Xslt.verify(Xslt.java:98) ~[gaulois-pipe-1.03.01.jar:?]
	at fr.efl.chaine.xslt.config.Pipe.verify(Pipe.java:77) ~[gaulois-pipe-1.03.01.jar:?]
	at fr.efl.chaine.xslt.config.Config.verify(Config.java:97) ~[gaulois-pipe-1.03.01.jar:?]
	at com.processing.step.GauloisPipeStep.run(GauloisPipeStep.java:128) ~[processing-0.0.2.jar:?]
	... 5 more
```

**Comment by cmarchand** [comment]
Try running GP with these parameters :

`-xmlDirPath file:/D:/08-ELS/15-CONVBIL/00-DATA/xml -workDirPath file:/D:/08-ELS/15-CONVBIL/00-DATA/work -originalXsltFilePath file:/D:/08-ELS/11-BOFIP/sie-efl-sgml2html/src/main/xslt/codescV2.xslt  -revisedXsltFilePath file:/D:/08-ELS/15-CONVBIL/01-DEV/sie-efl-sgml2html/src/main/xslt/codescV2.xslt`

**Comment by cmarchand** [comment]
Or, better, launch me a ZIP file, with a .bat, that I could reproduce exactly your problem.

**Comment by karrayhamdi** [comment]
[tnr-0.0.2-SNAPSHOT-linux.tar.gz](https://github.com/cmarchand/gaulois-pipe/files/1846981/tnr-0.0.2-SNAPSHOT-linux.tar.gz)

script Run with 4 param as file path. Thanks :)

**Comment by cmarchand** [comment]
And I run this on WHAT ?
I can not understand why you open an issue with windows-like file pathes problems, and give a sample program call xxx-linux-xxx with a bash script in...

**Comment by cmarchand** [comment]
Problem identified.

**Comment by cmarchand** [comment]
Release 1.03.04-RC4 published. You have to wait a little bit to be synchronized on maven central.
Watch [http://repo1.maven.org/maven2/top/marchand/xml/gaulois-pipe/](http://repo1.maven.org/maven2/top/marchand/xml/gaulois-pipe/)

**Comment by karrayhamdi** [comment]
perfect :)
