### ISSUE TITLE
Error code not returned if an exception occurs

### ISSUE THREAD

**Issue by arkamy** [cmarchand/gaulois-pipe#5]
With the following shell, 0 is always returned as error code even if an exception occurs :
`java -cp ... fr.efl.chaine.xslt.GauloisPipe ...`
`error=$?`
`echo "Error code gaulois-pipe : $error"`

**Comment by cmarchand** [comment]
This should be corrected with commit 19fb09b.
Could you check if this is correct ? Next build at ELS will occurs saturday at 2AM UT+1, but you can checkout and build by yourself.

Thanks in advance,
Christophe

**Comment by arkamy** [comment]
Thanks
I tried but It doesn't work. I know that I use the new version of Gaulois-pipe because if no exception occurs, the following new log info is displayed : 
`... fr.efl.chaine.xslt.GauloisPipe     - Gaulois-Pipe is exiting without error.`

But with or without exception, I receive the same error code : 0

Code : 
`java -cp ... fr.efl.chaine.xslt.GauloisPipe ...`
`error=$?`
`echo "***** GAULOIS-PIPE : ERROR = $? *******"`

Result : 
`fr.efl.chaine.xslt.InvalidSyntaxException: ...`
`        at fr.efl.chaine.xslt.config.CfgFile.verify(CfgFile.java:42)`
`        ...`
`        at fr.efl.chaine.xslt.GauloisPipe.main(GauloisPipe.java:711)`
`***** GAULOIS-PIPE : ERROR = 0 *******`

Thanks in advance

**Comment by cmarchand** [comment]
Could you attach the config file you use to produce this ?

Best,
Christophe

**Comment by arkamy** [comment]
I found the problem. Bash doesn't accept negative error code (see http://www.perlmonks.org/?node_id=690533) Every negative status is interpreted as 0.
I use System.exit(1) instead of System.exit(-1) and it's OK

**Comment by cmarchand** [comment]
Should be solved in 1.03.03.
