### ISSUE TITLE
Add a choose step

### ISSUE THREAD

**Issue by cmarchand** [cmarchand/gaulois-pipe#6]
The idea is to have a step, which can choose between various XSLT, on a per-input file basis, according to a XPath test.
Something like :
```
<pipe>
   <xslt href="first.xsl"/>
   <choose>
      <when test="/*/local-name eq 'root1'><xslt href="1.xsl"/></when>
      <when test="/*/local-name eq 'root2'><xslt href="2.xsl"/></when>
      <otherwise><xslt href="3.xsl"/></otherwise>
   </choose>
   <xslt href="last.xsl"/>
</pipe>
```
For each input file, when constructing the pipeline, and based on the name of root element, `1.xsl`, `2.xsl` or `3.xsl` is inserted in the pipeline, between first.xsl and last.xsl

**Comment by Marc95** [comment]
the test is based on the result of the last <xslt or on the input file of the pipe?
Marc

**Comment by Marc95** [comment]
And perhaps to add the possibility to test a parameter value?
I think about a mode (print, web, etc ...) or a status (debug, etc ...)

**Comment by cmarchand** [comment]
As I see the implementation, It'll be impossible to query the previous result, so I think it's better to base the tests on the input document. And it won't be difficult to use a parameter value.
Is `$param gt 12` a valid XPath expression ?

**Comment by Marc95** [comment]
If you put all the parameters after GP evaluation in the context of XPath execution, the answer is yes!
In the idea on simplification, perhaps it should be could to have some nickname for the intern java classe like <choose> ;) !!!

**Comment by cmarchand** [comment]
Done.
Commit #66c6eb5
Any opinion on this will be appreciated.
