### ISSUE TITLE
input-name parameter

### ISSUE THREAD

**Issue by Marc95** [cmarchand/gaulois-pipe#9]
I try to use the input name parameter, to not use the base-uri() function in the xslt pipes.
  <xsl:param name="input-name" select="tokenize(base-uri(.),'/')[position()=last()]"></xsl:param>
  <xsl:param name="input-basename" select="string-join(tokenize($input-name,'\.')[position() &lt; last()],'.')"></xsl:param>
I don't put anything in the gaulois-pipe configuration.
But there is no value in the xslt second file of the pipe.
Is it the right way to do that?

**Comment by cmarchand** [comment]
See https://github.com/cmarchand/gaulois-pipe/blob/master/src/test/resources/substitution.xml

It calls parallel.xsl, which declares 2 parameters. 
One is set via //params/param, the other one by //sources/file.
You can set also parameters via command line argument.

A parameter defined in //xsl is given all the time.
A parameter defined in //params/param or via command-line is given to all XSL, java-steps, and so on.
A parameter defined in //sources/file is given to all XSL / java steps that process this file.

Best regards,
Christophe

**Comment by Marc95** [comment]
I understood that there always parameter set by the pipe, this are parameter concerning the input file, because of the base-uri() isn't set else in the first xsl file of the pipe.
One of this parameter is input-name, isn't it?

**Comment by cmarchand** [comment]
No, there is no input-name parameter given to XSL.

But there is a pseudo-variable that you can use:
`   <param name="foe" value="$[input-name]"/>`
This will set xsl param named foe with the name of the input file processed.
Other pseudo-variables are input-basename, which is the input file name without extension, and inut-extension, which is the input file name extension.

But input files are loaded via saxon builder (http://www.saxonica.com/documentation/#!javadoc/net.sf.saxon.s9api/DocumentBuilder@build) :
`builder.build(input.getFile());`
So, in the first XSL of the pipe, base-uri() should be available. If not, please file a new issue.
